.TH NOCT 1 "July 2025" "NoctVM Project" "User Commands"
.SH NAME
noct \- command-line interface for NoctLang

.SH SYNOPSIS
.B noct
[\fIOPTIONS\fR]
[\fIfile\fR]

.SH DESCRIPTION
\fBnoct\fR is a command-line frontend for NoctLang.

.SH OPTIONS
.TP
.BR --disable-jit
Disable JIT compilation and run in the bytecode interpretation mode.

.TP
.BR --compile
Compile sources to bytecode files.

.TP
.BR --ansic
Transpile sources into a C source code.

.TP
.BR --elisp
Transpile sources into an Emacs Lisp source code.

.SH EXAMPLES
.TP
Run REPL:
.B
noct

.TP
Run a NoctLang program:
.B
noct script.noct

.TP
Compile a NoctLang source file to a C source file:
.B
noct --ansic out.c script.noct

.TP
Compile a NoctLang source file to an Emacs Lisp source file:
.B
noct --ansic out.el script.noct

.SH AUTHOR
Written by Awe Morris.

.SH COPYRIGHT
Copyright © 2025 Awe Morris.  
This is free software; see the source for copying conditions.  
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
