#!/usr/bin/env python3
"""Generate FFI tables, the elisp shim and the transpiler ns-map from napi.def.

Outputs (under the directory given as argv[2], default: generated/):
  napi-table.inc   C: forward decls + ffi_item table for impl=c rows
  noct-shim.el     elisp: adapters for shim=adapt rows + dialect runtime
  elisp-ns-map.txt transpiler namespace map (Editor.x -> emacs name)
  napi-scope.txt   all callable Editor.* names, for the scope lint
"""

import re
import sys
import os


def kebab(camel: str) -> str:
    """gotoChar -> goto-char, bufferModifiedP -> buffer-modified-p"""
    out = re.sub(r'(?<!^)(?=[A-Z])', '-', camel)
    return out.lower()


def parse(path):
    rows = []
    with open(path, encoding='utf-8') as f:
        for lineno, raw in enumerate(f, 1):
            line = raw.split('#', 1)[0].rstrip()
            if not line.strip():
                continue
            cols = [c.strip() for c in line.split('\t') if c.strip()]
            if len(cols) < 5:
                sys.exit(f"napi.def:{lineno}: expected 5 columns, got {len(cols)}: {raw!r}")
            noct, emacs, impl, shim, args = cols[:5]
            if impl not in ('c', 'noct'):
                sys.exit(f"napi.def:{lineno}: bad impl {impl!r}")
            if shim not in ('direct', 'adapt'):
                sys.exit(f"napi.def:{lineno}: bad shim {shim!r}")
            derived = kebab(noct)
            if emacs == '-':
                emacs = derived
            elif emacs == derived:
                sys.exit(f"napi.def:{lineno}: emacs name {emacs!r} is mechanical; write '-'")
            arglist = [] if args == '-' else [a.strip() for a in args.split(',')]
            rows.append(dict(noct=noct, emacs=emacs, impl=impl,
                             shim=shim, args=arglist, line=lineno))
    names = [r['noct'] for r in rows]
    dup = {n for n in names if names.count(n) > 1}
    if dup:
        sys.exit(f"napi.def: duplicate names: {sorted(dup)}")
    return rows


def gen_c_table(rows):
    c_rows = [r for r in rows if r['impl'] == 'c']
    out = ["/* Generated by tools/gen-napi.py from src/napi.def. Do not edit. */", ""]
    if not c_rows:
        out.append("/* No C-implemented functions. */")
        return '\n'.join(out) + '\n'

    for r in c_rows:
        out.append(f"static bool cfunc_Editor_{r['noct']}(NoctEnv *env);")
    out.append("")
    out.append("static struct ffi_item editor_ffi_items[] = {")
    for r in c_rows:
        args = r['args']
        argc = len(args)
        argstr = ', '.join(f'"{a}"' for a in args) if args else 'NULL'
        out.append(f'\t{{"Editor.{r["noct"]}", "Editor", "{r["noct"]}", '
                   f'{argc}, {{{argstr}}}, cfunc_Editor_{r["noct"]}}},')
    out.append("};")
    out.append("")
    return '\n'.join(out)


def gen_ns_map(rows):
    out = ["# Generated by tools/gen-napi.py. Namespace map for noct --elisp.",
           "# Editor.<noct> -> <emacs form to call>"]
    for r in rows:
        target = r['emacs'] if r['shim'] == 'direct' else f"noct--{r['emacs']}"
        out.append(f"Editor.{r['noct']}\t{target}")
    return '\n'.join(out) + '\n'


def gen_shim(rows):
    out = [";; Generated by tools/gen-napi.py from src/napi.def. Do not edit.",
           ";; Runtime support for running transpiled Noct test programs",
           ";; inside GNU Emacs (the test oracle).",
           "",
           ";; --- Noct dialect runtime ---",
           "",
           "(defun noct-truthy (x)",
           "  \"Noct truthiness: nil and numeric zero are false.\"",
           "  (not (or (null x) (eql x 0))))",
           "",
           "(defun noct-bool (x) (if x 1 0))",
           "",
           "(defun noct-lt (a b)",
           "  (noct-bool (if (stringp a) (string< a b) (< a b))))",
           "(defun noct-lte (a b)",
           "  (noct-bool (if (stringp a) (not (string< b a)) (<= a b))))",
           "(defun noct-gt (a b)",
           "  (noct-bool (if (stringp a) (string< b a) (> a b))))",
           "(defun noct-gte (a b)",
           "  (noct-bool (if (stringp a) (not (string< a b)) (>= a b))))",
           "(defun noct-eq (a b) (noct-bool (equal a b)))",
           "(defun noct-neq (a b) (noct-bool (not (equal a b))))",
           "(defun noct-not (a) (noct-bool (not (noct-truthy a))))",
           "",
           ";; Frozen-dict machinery is a VM-side concern; identity here.",
           "(defun Dict.freeze (d) d)",
           "(defun Global.markConst (name) name)",
           "",
           "(defmacro noct-and (a b)",
           "  `(if (noct-truthy ,a) (noct-bool (noct-truthy ,b)) 0))",
           "(defmacro noct-or (a b)",
           "  `(if (noct-truthy ,a) 1 (noct-bool (noct-truthy ,b))))",
           "",
           "(defun noct-add (a b)",
           "  \"Noct +: string concatenation when either side is a string.\"",
           "  (if (or (stringp a) (stringp b))",
           "      (concat (noct-to-string a) (noct-to-string b))",
           "    (+ a b)))",
           "",
           "(defun noct-to-string (x)",
           "  (cond ((stringp x) x)",
           "        ((eq x t) \"1\")",
           "        ((null x) \"0\")",
           "        ((numberp x) (number-to-string x))",
           "        (t (format \"%s\" x))))",
           "",
           ";; Arrays are lists; subscripts are 0-based reads.",
           "(defun noct-array (a i) (nth i a))",
           "",
           ";; Dictionaries are alists built with (list (cons ...)).",
           "(defmacro noct-dot (obj key)",
           "  `(cdr (assq \',key ,obj)))",
           "(defmacro noct-dot-assign (obj key val)",
           "  `(let ((cell (assq \',key ,obj)))",
           "     (if cell (setcdr cell ,val)",
           "       (nconc ,obj (list (cons \',key ,val))))))",
           "",
           "(defun oracleEmit (x)",
           "  \"The single observation function of the oracle harness.\"",
           "  (princ (noct-to-string x))",
           "  (terpri))",
           "",
           ";; --- adapters (shim=adapt rows) ---",
           ""]

    # Hand-written adapter bodies, keyed by the Emacs function name.
    # An adapt row without an entry gets a passthrough with a TODO.
    bodies = {
        'char-after': '(or (char-after pos) 0)',
        'char-before': '(or (char-before pos) 0)',
        'insert-file-contents': '(cadr (insert-file-contents file))',
        'write-region': '(progn (write-region start end file nil \'silent) 0)',
        'set-buffer-modified-p':
            '(progn (set-buffer-modified-p (not (eql flag 0))) flag)',
        'buffer-file-name': '(or (buffer-file-name) "")',
        'marker-position': '(or (marker-position m) 0)',
        'mark': '(or (mark t) 0)',
        'kill-append': '(kill-append s nil)',
        'search-forward': '(or (search-forward s nil t) 0)',
        'search-backward': '(or (search-backward s nil t) 0)',
        're-search-forward': '(or (re-search-forward s nil t) 0)',
        're-search-backward': '(or (re-search-backward s nil t) 0)',
        'match-beginning': '(or (match-beginning n) 0)',
        'match-end': '(or (match-end n) 0)',
        'replace-string': '(progn (replace-string from to) 0)',
        'replace-regexp': '(progn (replace-regexp pat to) 0)',
        'expand-file-name': '(expand-file-name name (if (equal dir "") nil dir))',
        'abbreviate-file-name': '(abbreviate-file-name name)',
        'file-name-directory': '(or (file-name-directory name) "")',
        'transpose-chars':
            '(progn (if (eolp) (forward-char -1)) (transpose-chars 1) 0)',
        'newline': '(progn (newline n) 0)',
    }
    for r in rows:
        if r['shim'] != 'adapt':
            continue
        args = r['args'] if r['args'] else []
        arglist = ' '.join(args)
        out.append(f"(defun noct--{r['emacs']} ({arglist})")
        if r['emacs'] in bodies:
            out.append(f"  {bodies[r['emacs']]})")
        else:
            out.append(f"  ;; TODO: adapt conventions for {r['emacs']}")
            call = f"({r['emacs']}{(' ' + arglist) if arglist else ''})"
            out.append(f"  {call})")
        out.append("")
    return '\n'.join(out) + '\n'


def gen_napi_init(rows):
    """editor code reaches the primitives as Editor.<name>; this builds
    the Editor dictionary from the bare Noct functions."""
    out = ["//",
           "// Generated by tools/gen-napi.py from src/napi.def. Do not edit.",
           "//",
           "",
           "func remacsInitCore() {",
           "    Editor = {"]
    entries = [f"        {r['noct']}: {r['noct']}" for r in rows]
    out.append(',\n'.join(entries))
    out.append("    };")
    out.append("    bufferInit();\n    killInit();\n    undoInit();\n    regexInit();\n    lispInit();")
    out.append("    return 0;")
    out.append("}")
    return '\n'.join(out) + '\n'


def gen_scope(rows):
    return '\n'.join(f"Editor.{r['noct']}" for r in rows) + '\n'


def gen_lisp_bridge(rows):
    out = ["//",
           "// Generated by tools/gen-napi.py from src/napi.def. Do not edit.",
           "// The Lisp bridge: every Editor primitive as a Lisp builtin,",
           "// keyed by its Emacs name with the call arity.",
           "//",
           "",
           "func lispBridgeInit() {",
           "    LispBridge = {};"]
    for r in rows:
        args = r['args'] if r['args'] else []
        out.append('    LispBridge["%s"] = { fn: Editor.%s, n: %d };'
                   % (r['emacs'], r['noct'], len(args)))
    out.append("    return 0;")
    out.append("}")
    return '\n'.join(out) + '\n'

def main():
    src = sys.argv[1] if len(sys.argv) > 1 else 'src/napi.def'
    outdir = sys.argv[2] if len(sys.argv) > 2 else 'generated'
    rows = parse(src)
    os.makedirs(outdir, exist_ok=True)
    with open(os.path.join(outdir, 'napi-table.inc'), 'w') as f:
        f.write(gen_c_table(rows))
    with open(os.path.join(outdir, 'elisp-ns-map.txt'), 'w') as f:
        f.write(gen_ns_map(rows))
    with open(os.path.join(outdir, 'noct-shim.el'), 'w') as f:
        f.write(gen_shim(rows))
    with open(os.path.join(outdir, 'napi-scope.txt'), 'w') as f:
        f.write(gen_scope(rows))
    with open(os.path.join(outdir, 'lisp-bridge.noct'), 'w') as f:
        f.write(gen_lisp_bridge(rows))
    with open(os.path.join(outdir, 'napi-init.noct'), 'w') as f:
        f.write(gen_napi_init(rows))
    c = sum(1 for r in rows if r['impl'] == 'c')
    print(f"napi.def: {len(rows)} functions ({c} in C, {len(rows)-c} in Noct)")


if __name__ == '__main__':
    main()
